language: python

python:
  - "3.4"
  - "3.3"
  - "3.2"
  - "pypy3"

before_install:
  - sudo apt-get install -qq build-essential

install:
  - pip install -r requirements.txt

script:
  - cd tests
  - py.test

notifications:
  email: false
